version: "3"
services:
    app:
        container_name: nric-generator
        build:
            context: .
            dockerfile: Dockerfile
        image: javonheng/nric-generator
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./:/usr/src/app